// Generated by Selenium IDE
const { Builder, By, Key} = require('selenium-webdriver')
const assert = require('assert')
var expect = require('chai').expect;
const chrome = require('selenium-webdriver/chrome');

const screen = {
    width: 640,
    height: 480
};

describe('Fazendo testes de UI', function() {
    this.timeout(30000)
    let driver
    let vars
    beforeEach(async function() {
        driver = await new Builder().forBrowser('chrome').build()
        vars = {}
    })

    afterEach(async function() {
        await driver.quit();
    })

    it('Testando site do CIn', async function() {
        await driver.get("https://www3.cin.ufpe.br/br/")
        await driver.findElement(By.css(".fa-search")).click()
        await driver.findElement(By.name("term")).click()
        await driver.findElement(By.name("term")).sendKeys("Busca teste")
        await driver.findElement(By.name("term")).sendKeys(Key.ENTER)
        
        await driver.getTitle().then(function(title){
            expect(title).equals("CIn - Centro de Informática da UFPE | Resultado da busca");
        });
    })

    it('Testando conversor de temperatura', async function(){

       //Isso aqui foi colocado pra ele esperar a resposta renderizar
        await driver.get("http://localhost:3030")
        await driver.findElement(By.id("de")).click()
        await driver.findElement(By.id("de")).sendKeys('C')
        await driver.findElement(By.id("para")).click()
        await driver.findElement(By.id("para")).sendKeys('F')
        await driver.findElement(By.id("valor")).click()
        await driver.findElement(By.id("valor")).sendKeys('123')
        await driver.findElement(By.id("button")).click()

        await driver.manage().setTimeouts( { implicit: 1000}) 

        var text = await driver.findElement(By.id('resp')).getText()

        assert.equal(text, '253.4')
    })
})