// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
var expect = require('chai').expect;
const chrome = require('selenium-webdriver/chrome');

const screen = {
    width: 640,
    height: 480
};

describe('TESTE', function() {
    this.timeout(30000)
    let driver
    let vars
    beforeEach(async function() {
        driver = await new Builder().forBrowser('chrome').build()
        vars = {}
    })

    afterEach(async function() {
        await driver.quit();
    })

    it('TESTE', async function() {
        await driver.get("https://www3.cin.ufpe.br/br/")
        await driver.findElement(By.css(".fa-search")).click()
        await driver.findElement(By.name("term")).click()
        await driver.findElement(By.name("term")).sendKeys("Busca teste")
        await driver.findElement(By.name("term")).sendKeys(Key.ENTER)

        await driver.getTitle().then(function(title){
            expect(title).equals("CIn - Centro de Informática da UFPE | Resultado da busca");
        });
    })
})